export const AdminActionTypes = {

    LOGIN_REQ : "LOGIN_REQ",
    LOGIN_REQ_SUCCESS : "LOGIN_REQ_SUCCESS",
    LOGIN_REQ_FAILED : "LOGIN_REQ_FAILED",

    LOGOUT_REQ : 'LOGOUT_REQ',

    GET_USERS_REQ : 'GET_USERS_REQ',
    GET_USERS_SUCCESS : "GET_USERS_SUCCESS",
    GET_USERS_FAILED : "GET_USERS_FAILED",


    ADD_BIKE_REQ : "ADD_BIKE_REQ",
    ADD_BIKE_SUCCESS : "ADD_BIKE_SUCCESS",
    ADD_BIKE_FAILED : "ADD_BIKE_FAILED",

    

    

}