export const ActionTypes = {

    REGISTER_REQUEST : "REGISTER_REQUEST",
    REGISTER_REQUEST_SUCCESS : "REGISTER_REQUEST_SUCCESS",
    REGISTER_REQUEST_FAILED : "REGISTER_REQUEST_FAILED",

    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_REQUEST_SUCCESS : "LOGIN_REQUEST_SUCCESS",
    LOGIN_REQUEST_FAILED : "LOGIN_REQUEST_FAILED",

    LOGOUT_REQUEST : "LOGOUT_REQUEST",


    HOME_REQUEST : "HOME_REQUEST",
    HOME_REQUEST_SUCCESS : "HOME_REQUEST_SUCCESS",
    HOME_REQUEST_FAILED : "HOME_REQUEST_FAILED",

    GET_PROFILE_REQUEST : "GET_PROFILE_REQUEST",
    GET_PROFILE_REQUEST_SUCCESS : 'GET_PROFILE_REQUEST_SUCCESS',
    GET_PROFILE_REQUEST_FAILED : "GET_PROFILE_REQUEST_FAILED",
    

    IMAGE_UPLOAD_REQ : "IMAGE_UPLOAD_REQ",
    IMAGE_UPLOAD_REQ_SUCCESS : "IMAGE_UPLOAD_REQ_SUCCESS",
    IMAGE_UPLOAD_REQ_FAILED : "IMAGE_UPLOAD_REQ_FAILED",

    UPDATE_PROFILE : "UPDATE_PROFILE",
    UPDATE_PROFILE_DETAILS : "UPDATE_PROFILE_DETAILS",


    GET_BIKES_REQ : "GET_BIKES_REQ",
    GET_BIKES_SUCCESS : "GET_BIKES_SUCCESS",
    GET_BIKES_FAILED : "GET_BIKES_FAILED",

    GET_LOCATION_REQ : "GET_LOCATION_REQ",
    GET_LOCATION_SUCCESS : "GET_LOCATION_SUCCESS",
    GET_LOCATION_FAILED : "GET_LOCATION_FAILED",

    GET_SEARCHED_BIKES_REQ : "GET_SEARCHED_BIKES_REQ",
    GET_SEARCHED_BIKES_SUCCESS : "GET_SEARCHED_BIKES_SUCCESS",
    GET_SEARCHED_BIKES_FAILED : "GET_SEARCHED_BIKES_FAILED"

    

    


    
    
}