export const ActionTypes = {

    REGISTER_REQUEST : "REGISTER_REQUEST",
    REGISTER_REQUEST_SUCCESS : "REGISTER_REQUEST_SUCCESS",
    REGISTER_REQUEST_FAILED : "REGISTER_REQUEST_FAILED",

    GOOGLE_SIGNUP_REQ : "GOOGLE_SIGNUP_REQ",
    GOOGLE_SIGNUP_SUCCESS : "GOOGLE_SIGNUP_SUCCESS",
    GOOGLE_SIGNUP_FAILED : "GOOGLE_SIGNUP_FAILED",

    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_REQUEST_SUCCESS : "LOGIN_REQUEST_SUCCESS",
    LOGIN_REQUEST_FAILED : "LOGIN_REQUEST_FAILED",

    LOGOUT_REQUEST : "LOGOUT_REQUEST",


    HOME_REQUEST : "HOME_REQUEST",
    HOME_REQUEST_SUCCESS : "HOME_REQUEST_SUCCESS",
    HOME_REQUEST_FAILED : "HOME_REQUEST_FAILED",

    GET_PROFILE_REQUEST : "GET_PROFILE_REQUEST",
    GET_PROFILE_REQUEST_SUCCESS : 'GET_PROFILE_REQUEST_SUCCESS',
    GET_PROFILE_REQUEST_FAILED : "GET_PROFILE_REQUEST_FAILED",
    

    IMAGE_UPLOAD_REQ : "IMAGE_UPLOAD_REQ",
    IMAGE_UPLOAD_REQ_SUCCESS : "IMAGE_UPLOAD_REQ_SUCCESS",
    IMAGE_UPLOAD_REQ_FAILED : "IMAGE_UPLOAD_REQ_FAILED",

    UPDATE_PROFILE : "UPDATE_PROFILE",
    UPDATE_PROFILE_DETAILS : "UPDATE_PROFILE_DETAILS",


    GET_BIKES_REQ : "GET_BIKES_REQ",
    GET_BIKES_SUCCESS : "GET_BIKES_SUCCESS",
    GET_BIKES_FAILED : "GET_BIKES_FAILED",

    GET_LOCATION_REQ : "GET_LOCATION_REQ",
    GET_LOCATION_SUCCESS : "GET_LOCATION_SUCCESS",
    GET_LOCATION_FAILED : "GET_LOCATION_FAILED",

    GET_SEARCHED_BIKES_REQ : "GET_SEARCHED_BIKES_REQ",
    GET_SEARCHED_BIKES_SUCCESS : "GET_SEARCHED_BIKES_SUCCESS",
    GET_SEARCHED_BIKES_FAILED : "GET_SEARCHED_BIKES_FAILED",


    GET_RENTED_BIKES_REQ : "GET_RENTED_BIKES_REQ",
    GET_RENTED_BIKES_SUCCESS : "GET_RENTED_BIKES_SUCCESS",
    GET_RENTED_BIKES_FAILED : "GET_RENTED_BIKES_FAILED",

    GET_ACCEPTED_BIKES_REQ : "GET_ACCEPTED_BIKES_REQ",
    GET_ACCEPTED_BIKES_SUCCESS : "GET_ACCEPTED_BIKES_SUCCESS",
    GET_ACCEPTED_BIKES_FAILED : "GET_ACCEPTED_BIKES_FAILED",

    GET_REJECTED_BIKES_REQ :"GET_REJECTED_BIKES_REQ",
    GET_REJECTED_BIKES_SUCCESS : "GET_REJECTED_BIKES_SUCCESS",
    GET_REJECTED_BIKES_FAILED : "GET_REJECTED_BIKES_FAILED",

    GET_PENDING_BIKES_REQ :"GET_PENDING_BIKES_REQ",
    GET_PENDING_BIKES_SUCCESS : "GET_PENDING_BIKES_SUCCESS",
    GET_PENDING_BIKES_FAILED : "GET_PENDING_BIKES_FAILED",

    BOOKING_REQ : "BOOKING_REQ",
    BOOKING_SUCCESS : "BOOKING_SUCCESS",
    BOOKING_FAILED : "BOOKING_FAILED",

    GET_RENTED_RIDES_REQ : "GET_RENTED_RIDES_REQ",
    GET_RENTED_RIDES_SUCCESS : "GET_RENTED_RIDES_SUCCESS",
    GET_RENTED_RIDES_FAILED : "GET_RENTED_RIDES_FAILED",

    CREATE_ORDER_REQ : "CREATE_ORDER_REQ",
    CREATE_ORDER_SUCCESS : "CREATE_ORDER_SUCCESS",
    CREATE_ORDER_FAILED : "CREATE_ORDER_FAILED",

    GET_WALLET_REQ : "GET_WALLET_REQ",
    GET_WALLET_SUCCESS : "GET_WALLET_SUCCESS",
    GET_WALLET_FAILED : "GET_WALLET_FAILED"

    

    

    

    


    
    
}